spring:
  application:
    name: job-service
  datasource:
    url: jdbc:mysql://localhost:3306/epitomehub
    username: epitome
    password: epitome
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
